###
### Using for AWS CODE BUILD
###

# version: 0.2

# env:
#   variables:
#     AWS_REGION: "us-east-1"
#     ACCOUNT_ID: "774492851500"
#     REPOSITORY_URI: "774492851500.dkr.ecr.us-east-1.amazonaws.com/ecocupid-dev-ui"

# phases:
#   pre_build:
#     commands:
#       - echo Log in to Amazon ECR...
#       - aws --version
#       - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
#       - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
#       - IMAGE_TAG=${COMMIT_HASH:=latest}
#   build:
#     commands:
#       - echo Building the Docker images...
#       - docker build -t $REPOSITORY_URI:latest .
#       - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
#   post_build:
#     commands:
#       - echo Build completed on `date`
#       - echo Pushing the Docker images...
#       - docker push $REPOSITORY_URI:latest
#       - docker push $REPOSITORY_URI:$IMAGE_TAG
#       - echo Writing image definitions file...
#       - printf '[{"name":"ecocupid-dev-ui","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
# artifacts:
#   files:
#     - '**/*'